# https://github.com/ReVanced/revanced-manager-compose/blob/dev/.github/workflows/release.yml

name: CI

on:
  workflow_dispatch:
  #pull_request:
    #paths-ignore:
  #     - "README*.md"
  #  types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Compile
        run: |
          ./gradlew assembleDebug

  prettier:
    name: Prettier fmt
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prettier
        run: npx prettier --check .
