name: Upload Artifacts

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            lfs: true

      - run: |
          git clone https://github.com/wiiznokes/libgit2-android --depth=1 --branch=patch-android

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Clone submodule
        run: |
          git submodule init
          git submodule update
      
      - name: Retrieve the secret and decode it to a file
        env:
          KEY_BASE64: ${{ secrets.KEY_BASE64 }}
        run: |
          echo $KEY_BASE64 | base64 --decode > app/key.jks


      - name: Build apk
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo $KEY_ALIAS
          echo $KEY_PASSWORD
          echo $STORE_PASSWORD
          cat app/key.jks
          ls app/
          ./gradlew assembleRelease

      # todo should sign
      # https://github.com/libre-tube/LibreTube/blob/master/.github/workflows/ci.yml

      - run: echo "DEB_NAME=$(basename ./packages/fan-control*.deb)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: gitnote
          path: app/build/outputs/apk/release/*.apk
